### ISSUE TITLE
Licensing issue with SMO

### ISSUE THREAD

**Issue by FilipDeVos** [appharbor/AppHarbor-SqlServerBulkCopy#7]
I noticed you include smo libraries in this repository. As far as I know this is not allowed by microsoft. To ship the SMO libraries you have to include the xmo setup. See a comment from MS in [this message](http://social.msdn.microsoft.com/Forums/en-US/sqlsmoanddmo/thread/99cdfe77-e410-486e-9a0e-f596421a400c)

Note that I don't have any connection with Microsoft nor represent them on this issue. Just trying to avoid you get into trouble. (once bitten, twice shy.)

**Comment by friism** [comment]
Thanks!, I'll look into it.

**Comment by friism** [comment]
I've removed the SMO dlls from the repo now.
